masterclass/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from masterclass import views
from masterclass import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="index"),
    path("video.html", views.videos, name="video"),
    path("quiz/<int:id>/", views.quiz, name="quiz"),
    path("quiz/correct.html", views.quiz_correct, name="quiz_correct"),
    path("quiz/wrong.html", views.quiz_wrong, name="quiz_wrong"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    #urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

masterclass/models.py
from django.db import models

class Video(models.Model):
    title = models.CharField(max_length=250)
    desc = models.TextField()
    video = models.FileField(upload_to="uploads/")

class Quiz(models.Model):
    name = models.CharField(max_length=250)
    video = models.ForeignKey("Video", on_delete="cascade")

    question1 = models.CharField(max_length=250)
    question2 = models.CharField(max_length=250)
    question3 = models.CharField(max_length=250)
    question4 = models.CharField(max_length=250)

    solution1 = models.BooleanField()
    solution2 = models.BooleanField()
    solution3 = models.BooleanField()
    solution4 = models.BooleanField()

    class Meta:
        verbose_name_plural = "Quizzes"

masterclass/forms.py
from django import forms

class Video(forms.Form):
    answer1 = forms.BooleanField(max_length=250)
    answer2 = forms.BooleanField(max_length=250)
    answer3 = forms.BooleanField(max_length=250)
    answer4 = forms.BooleanField(max_length=250)

masterclass/views.py
from django.http import HttpResponse
from django.shortcuts import redirect
from django.template import loader
from masterclass import models

def index(request):
    template = loader.get_template("masterclass/index.html")

    return HttpResponse(template.render({}, request))

def videos(request):
    template = loader.get_template("masterclass/video.html")
    videos = models.Video.objects.all()

    if request.method == "POST":
        id = request.POST["id"]
        model = models.Quiz.objects.filter(video__id=id).first()
        print(id,model)
        expectedAnswers = []
        for i in range(1,5):
            _get_answers(model, i, expectedAnswers)

        answers = request.POST.getlist("answer", [])
        if sorted(answers) == sorted(expectedAnswers):
            return redirect("quiz_correct")
        else:
            return redirect("quiz_wrong")

    return HttpResponse(template.render({
        "videos": videos,
    }, request))


def _get_answers(model, i, expected):
    if getattr(model, "solution{}".format(i)): 
        expected.append("answer{}".format(i))
    

def quiz(request, id):
    template = loader.get_template("masterclass/quiz.html")
    model = models.Quiz.objects.get(pk=id)

    if request.method == "POST":
        expectedAnswers = []
        for i in range(1,5):
            _get_answers(model, i, expectedAnswers)

        answers = request.POST.getlist("answer", [])
        if sorted(answers) == sorted(expectedAnswers):
            return redirect("quiz_correct")
        else:
            return redirect("quiz_wrong")

    return HttpResponse(template.render({"quiz": model}, request))

def quiz_wrong(request):
    template = loader.get_template("masterclass/validation.html")
    return HttpResponse(template.render({"correct": False}, request))

def quiz_correct(request):
    template = loader.get_template("masterclass/validation.html")
    return HttpResponse(template.render({"correct": True}, request))

masterclass/templates/masterclass/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="/static/css/style.css">
        <title>Masterclass</title>
    </head>

    <body>
        <!-- Navbar start -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light container">
            <a class="navbar-brand" href="#">
                <img src="/static/img/logo.png" alt="Relevatico logo">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Newest <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Category
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">Cat 1</a>
                            <a class="dropdown-item" href="#">Cat 2</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Most Popular</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Learning Concepts</a>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0 mx-2">
                    <a href="/admin/" class="btn btn-login">Log in</a>
                    <button type="button" name="sign up" class="btn btn-signup">Sign up</button>
                </form>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search ..." aria-label="Search">
                </form>
            </div>
        </nav>
        <!-- Navbar end -->

        <div class="container">
            <div class="row">
                <div class="col">
                    <!-- Header image -->
                    <div class="card text-black my-2" >
                        <img src="/static/img/header.jpg" class="card-img large">
                        <div class="card-img-overlay d-flex flex-column">
                            <div class="mt-auto">
                                <h1 class="card-title">Relevatico</h1>
                                <p class="card-text subtitle">A Platform for disgtributing scientific content to spreatd awareness about major global problems.</p>
                                <a role="button" class="btn btn-videos" href="video.html">View videos</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row d-flex flex-row justify-content-between align-items-stretch align-content-stretch flex-nowrap my-2">
                <!-- topic cards -->
                <div class="card text-white flex-even mx-2  ">
                    <img src="/static/img/board.jpg" alt="" class="card-img" ">
                    <div class="card-img-overlay d-flex flex-column">
                        <h2 class="card-title mt-auto">Lack of education</h2>
                    </div>
                </div>
                <div class="card text-white flex-even mx-2  ">
                    <img src="/static/img/ice.jpg" alt="" class="card-img" >
                    <div class="card-img-overlay d-flex flex-column">
                        <h2 class="card-title mt-auto">Pollution</h2>
                    </div>
                </div>
                <div class="card text-white flex-even mx-2  ">
                    <img src="/static/img/protest.jpg" alt="" class="card-img" >
                    <div class="card-img-overlay d-flex flex-column">
                        <h2 class="card-title mt-auto">Freedom of speech</h2>
                    </div>
                </div>
                <div class="card text-white flex-even mx-2 ">
                    <img src="/static/img/security.jpg" alt="" class="card-img left" >
                    <div class="card-img-overlay d-flex flex-column">
                        <h2 class="card-title mt-auto">Security</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <!-- Header image -->
                    <div class="card text-black my-2" >
                        <img src="/static/img/education.jpg" class="card-img">
                        <div class="card-img-overlay d-flex flex-column text-white">
                            <div class="mt-auto">
                                <h1 class="card-title">Gender equality</h1>
                                <p class="card-text">Although women make up approximately half of the population,
there have historically been social barriers to economic
and personal freedom for women.</p>
                                <a role="button" class="btn btn-videos" href="video.html">View videos</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- footer -->
        <footer class="footer">
            <div class="container px-4">
                <div class="row justify-content-between">
                    <div class="col-4 d-flex flex-column justify-content-between">
                        <a role="button" class="btn btn-footer my-1">Contact</a>
                        <a role="button" class="btn btn-footer my-1">How it works</a>
                        <a role="button" class="btn btn-footer my-1">FAQ</a>
                        <a role="button" class="btn btn-footer my-1">Press</a>
                    </div>
                    <div class="col-4 d-flex flex-column justify-content-between">
                        <a role="button" class="btn btn-footer my-1">Language</a>
                        <a href="#">Privacy Policy</a>
                        <a href="#">Terms & Conditions</a>
                        <p>Relevatico Company &copy 2019</p>
                    </div>
                </div>
            </div>
        </footer>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

masterclass/templates/masterclass/quiz.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="description" content="">
  <meta name="keywords" content="">
  <meta name="theme-color" content="#FFA000">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
  <meta http-equiv="x-dns-prefetch-control" content="on">
  <link rel="dns-prefetch" href="//fonts.googleapis.com">
  <link rel="dns-prefetch" href="//cdnjs.cloudflare.com">
  
  <link rel="stylesheet" type="text/css" href="/static/css/quizStyle.css"> <!-- specific stlyesheet-->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,400i,700,700i&display=swap&subset=latin-ext" rel="stylesheet">
  <link rel="canonical" href="/">
  <title>Relevatico</title>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
</head>
<body>
  <div class="quiz-section">
    <form method="POST">
    <h2 class="quiz-question">{{ quiz.name }}</h2>
    <div id="answer_1" class="quiz-answer">
      <input class="answer-input" type="checkbox" name="answer" value="answer1">
      <p class="answer-text">{{ quiz.question1 }}</p>
    </div>
    <div id="answer_2" class="quiz-answer">
      <input class="answer-input" type="checkbox" name="answer" value="answer2">
      <p class="answer-text">{{ quiz.question2 }}</p>
    </div>
    <div id="answer_3" class="quiz-answer">
      <input class="answer-input" type="checkbox" name="answer" value="answer3">
      <p class="answer-text">{{ quiz.question3 }}</p>
    </div>
    <div id="answer_4" class="quiz-answer">
      <input class="answer-input" type="checkbox" name="answer" value="answer4">
      <p class="answer-text">{{ quiz.question4 }}</p>
    </div>
    {% csrf_token %}
    <input type="submit" value="Submit Quiz">
    </form>
  </div>
</body>
</html>

masterclass/templates/masterclass/validation.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="/static/css/style.css">
        <title>Masterclass</title>
    </head>

    <body>
        <!-- Navbar start -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light container">
            <a class="navbar-brand" href="/">
                <img src="/static/img/logo.png" alt="Relevatico logo">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Newest <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Category
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">Cat 1</a>
                            <a class="dropdown-item" href="#">Cat 2</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Most Popular</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Learning Concepts</a>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0 mx-2">
                    <button type="button" name="log in" class="btn btn-login">Log in</button>
                    <button type="button" name="sign up" class="btn btn-signup">Sign up</button>
                </form>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search ..." aria-label="Search">
                </form>
            </div>
        </nav>
        <!-- Navbar end -->

        <div class="container my-4">
		{% if correct %}
            <div class="alert alert-success" role="alert">
                You are right!
            </div>
	    {% else %}
            <div class="alert alert-danger" role="alert">
                Try again!
            </div>
	    {% endif %}
            <a role="button" class="btn btn-login" onclick="history.back()">Back</a>
        </div>

        <!-- footer -->
        <footer class="footer">
            <div class="container px-4">
                <div class="row justify-content-between">
                    <div class="col-4 d-flex flex-column justify-content-between">
                        <a role="button" class="btn btn-footer my-1">Contact</a>
                        <a role="button" class="btn btn-footer my-1">How it works</a>
                        <a role="button" class="btn btn-footer my-1">FAQ</a>
                        <a role="button" class="btn btn-footer my-1">Press</a>
                    </div>
                    <div class="col-4 d-flex flex-column justify-content-between">
                        <a role="button" class="btn btn-footer my-1">Language</a>
                        <a href="#">Privacy Policy</a>
                        <a href="#">Terms & Conditions</a>
                        <p>Relevatico Company &copy 2019</p>
                    </div>
                </div>
            </div>
        </footer>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

masterclass/templates/masterclass/video.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="/static/css/quizStyle.css"> <!-- quiz stlyesheet-->
        <link rel="stylesheet" href="/static/css/style.css">
        <title>Masterclass</title>
    </head>

    <body>
        <!-- Navbar start -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light container">
            <a class="navbar-brand" href="/">
                <img src="/static/img/logo.png" alt="Relevatico logo">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Newest <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Category
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">Cat 1</a>
                            <a class="dropdown-item" href="#">Cat 2</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Most Popular</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Learning Concepts</a>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0 mx-2">
                    <a href="/admin/" class="btn btn-login">Log in</a>
                    <button type="button" name="sign up" class="btn btn-signup">Sign up</button>
                </form>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search ..." aria-label="Search">
                </form>
            </div>
        </nav>
        <!-- Navbar end -->

	{% for video in videos %}
        <div class="container my-4">
            <div class="accordion" id="topicExample">
                <div class="card w-100">
			<div class="card-header" id="video-header{{ video.id }}">
                        <h2>
				<button class="btn btn-link" type="button" data-toggle="collapse" data-target="#video{{ video.id }}" aria-expanded="false" aria-controls="video{{ video.id }}">
				    Video: {{ video.title }}
                            </button>
                        </h2>
                    </div>
		    <div id="video{{ video.id }}" class="collapse" aria-labelledby="video-header" data-parent="#topicExample">
                        <div class="card-body">
				<video src="{{ video.video.url }}" controls type="media/webm" class="card-img-top">
                                Your browser does not support this video!
                            </video>
			    <h2 class="text-orange">{{ video.title }}</h2>
                        </div>
                    </div>
                </div>
                <div class="card w-100">
                    <div class="card-header" id="description-header">
                        <h2>
				<button class="btn btn-link" type="button" data-toggle="collapse" data-target="#description{{video.id}}" aria-expanded="false" aria-controls="description">
                                Description
                            </button>
                        </h2>
                    </div>
		    <div id="description{{video.id}}" class="collapse" aria-labelledby="description-header" data-parent="#topicExample">
                        <div class="card-body">
                            <p>Some helpful description.</p>
                        </div>
                    </div>
                </div>
                <div class="card w-100">
                    <div class="card-header" id="quiz-header">
                        <h2>
				<button class="btn btn-link" type="button" data-toggle="collapse" data-target="#quiz{{video.id}}" aria-expanded="false" aria-controls="quiz">
                                Quiz
                            </button>
                        </h2>
                    </div>
		    <div id="quiz{{video.id}}" class="collapse" aria-labelledby="quiz-header" data-parent="#topicExample">
			{% with quiz=video.quiz_set.all.first %}
<form method="POST">
  <div class="quiz-section">
    <h2 class="quiz-question">{{ quiz.name }}</h2>
    <div id="answer_1" class="quiz-answer">
	    <input id="answerInput1-{{video.id}}" class="answer-input" type="checkbox" name="answer" value="answer1">
	    <label for="answerInput1-{{video.id}}" class="answer-text">{{ quiz.question1 }}</label>
    </div>
    <div id="answer_2" class="quiz-answer">
	    <input id="answerInput2-{{video.id}}" class="answer-input" type="checkbox" name="answer" value="answer2">
      <label for="answerInput2-{{video.id}}" class="answer-text">{{ quiz.question2 }}</label>
    </div>
    <div id="answer_3" class="quiz-answer">
	    <input id="answerInput3-{{video.id}}" class="answer-input" type="checkbox" name="answer" value="answer3">
	    <label for="answerInput3-{{video.id}}" class="answer-text">{{ quiz.question3 }}</label>
    </div>
    <div id="answer_4" class="quiz-answer">
	    <input id="answerInput4-{{video.id}}" class="answer-input" type="checkbox" name="answer" value="answer4">
	    <label for="answerInput4-{{video.id}}" class="answer-text">{{ quiz.question4 }}</label>
    </div>
  </div>
<div class="quiz-answer">
{% csrf_token %}
<input type="hidden" name="id" value="{{ video.id }}">
	<input type="submit" value="Submit quiz" class="btn btn-primary">
</div>
</form>

			{% endwith %}
                    </div>
                </div>
            </div>
        </div>
	{% endfor %}

        <!-- footer -->
        <footer class="footer">
            <div class="container px-4">
                <div class="row justify-content-between">
                    <div class="col-4 d-flex flex-column justify-content-between">
                        <a role="button" class="btn btn-footer my-1">Contact</a>
                        <a role="button" class="btn btn-footer my-1">How it works</a>
                        <a role="button" class="btn btn-footer my-1">FAQ</a>
                        <a role="button" class="btn btn-footer my-1">Press</a>
                    </div>
                    <div class="col-4 d-flex flex-column justify-content-between">
                        <a role="button" class="btn btn-footer my-1">Language</a>
                        <a href="#">Privacy Policy</a>
                        <a href="#">Terms & Conditions</a>
                        <p>Relevatico Company &copy 2019</p>
                    </div>
                </div>
            </div>
        </footer>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>